name: Lint Code Base

on:
  push:
    branches:
      - main  # Runs on push to the `main` branch
  pull_request:
    branches:
      - main  # Runs on pull request to the `main` branch

jobs:
  lint:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu image
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up Node.js (you can specify the version you need)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set to your desired Node.js version

      # Install dependencies (e.g., ESLint and your project's dependencies)
      - name: Install dependencies
        run: |
          cd frontend && npm install

      # Run ESLint on your codebase
      - name: Run ESLint
        run: |
          cd frontend && npm run lint  # Runs ESLint on the whole project directory
        continue-on-error: true  # Continue the workflow even if ESLint fails
